task_name: forecast
is_training: 1
root_path: ./dataset/ETT-small/
data_path: ETTh2.csv
model_id: ETTh2
n_vars: 7
model: TSMA
data: MultivariateDatasetBenchmark
input_token_len: 384
output_token_len: 96
d_ff: 2048
gpu: 0
tmax: 10
valid_last: True
seq_len: 768
test_seq_len: 768
test_pred_len: 96
train_epochs: 10
use_norm: True
batch_size: 32
d_model: 512
e_layers: 1
learning_rate: 0.0001
dim_R: 128