task_name: forecast
is_training: 1
root_path: ./dataset/Solar/
data_path: solar_AL.txt
model_id: solar
n_vars: 137
model: TSMA
data: MultivariateDatasetBenchmark
input_token_len: 128
output_token_len: 96
d_ff: 2048
gpu: 0
tmax: 10
valid_last: True
seq_len: 768
test_seq_len: 768
test_pred_len: 96
train_epochs: 10
use_norm: True
batch_size: 64
d_model: 128
e_layers: 1
learning_rate: 0.0001
cosine: True
dim_R: 128