task_name: forecast
is_training: 1
root_path: ./dataset/weather/
data_path: weather.csv
model_id: weather
n_vars: 21
model: TSMA
data: MultivariateDatasetBenchmark
input_token_len: 64
output_token_len: 96
d_ff: 2048
gpu: 0
tmax: 10
valid_last: True
seq_len: 768
test_seq_len: 768
test_pred_len: 96
train_epochs: 10
use_norm: False
batch_size: 128
d_model: 128
e_layers: 4
learning_rate: 0.0001
dim_R: 512