task_name: forecast
is_training: 1
root_path: ./dataset/electricity/
data_path: electricity.csv
model_id: electricity
n_vars: 321
model: TSMA
data: MultivariateDatasetBenchmark
input_token_len: 48
output_token_len: 48
d_ff: 2048
gpu: 0
tmax: 10
valid_last: True
seq_len: 96
test_seq_len: 96
test_pred_len: 96
train_epochs: 10
use_norm: True
batch_size: 8
d_model: 512
e_layers: 5
learning_rate: 0.0005
cosine: True
dim_R: 128
save_R: True