task_name: forecast
is_training: 1
#root_path: ./dataset/UTSD-full-npy/
#data_path: pretrain.npy
#model_id: utsd
root_path: ./dataset/ETT-small/
data_path: ETTh1.csv
model_id: ETTh1
n_vars: 1
model: TSMA
#data: Utsd_Npy
data: UnivariateDatasetBenchmark
input_token_len: 96
output_token_len: 96
d_ff: 2048
gpu: 0
tmax: 10
valid_last: True
seq_len: 2880
test_seq_len: 2880
test_pred_len: 96
train_epochs: 10
use_norm: True
#batch_size: 16384
batch_size: 1
d_model: 1024
e_layers: 8
learning_rate: 0.0001
cosine: True
dim_R: 1024
#dp: True
#devices: 0,1,2,3,4,5,6,7

adaptation: True
pretrain_model_path: ./checkpoints/forecast_era5_pretrain_TSMA_Era5_Pretrain_sl3072_it96_ot96_lr0.0001_bt10240_wd0_el8_dm1024_dff2048_nh8_cosTrue_test_0_dR1024/checkpoint.pth