task_name: forecast
is_training: 1
root_path: ./dataset/UTSD-full-npy/
data_path: pretrain.npy
model_id: utsd
n_vars: 1
model: TSMA
data: Utsd_Npy
input_token_len: 96
output_token_len: 96
d_ff: 2048
gpu: 0
tmax: 10
valid_last: True
seq_len: 2880
test_seq_len: 2880
test_pred_len: 96
train_epochs: 10
use_norm: True
batch_size: 16384
d_model: 1024
e_layers: 8
learning_rate: 0.0001
cosine: True
dim_R: 512
dp: True
devices: 0,1,2,3