task_name: forecast
is_training: 1
root_path: ./dataset/ERA5-Large/
data_path: pretrain.npy
model_id: era5_pretrain
n_vars: 1
model: TSMA
data: Era5_Pretrain
input_token_len: 96
output_token_len: 96
d_ff: 2048
gpu: 0
tmax: 10
valid_last: True
seq_len: 3072
test_seq_len: 3072
test_pred_len: 96
train_epochs: 10
use_norm: True
batch_size: 40960
d_model: 1024
e_layers: 8
learning_rate: 0.0001
cosine: True
dim_R: 1024
dp: True
devices: 0,1,2,3,4,5,6,7