task_name: forecast
is_training: 1
root_path: ./dataset/traffic/
data_path: traffic.csv
model_id: traffic
n_vars: 862
model: gpt4ts
data: MultivariateDatasetBenchmark
input_token_len: 96
output_token_len: 96
d_ff: 2048
gpu: 0
tmax: 10
valid_last: True
seq_len: 768
test_seq_len: 768
test_pred_len: 96
train_epochs: 10
use_norm: True
batch_size: 4
d_model: 768
e_layers: 4
learning_rate: 0.0005
cosine: True
dp: True
devices: 0,1,2,3